# Generated by Django 4.2.30 on 2026-05-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motociclista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido Materno')),
                ('apodo', models.CharField(blank=True, max_length=100, verbose_name='Apodo / Alias')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Tipo de Sangre')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado_republica', models.CharField(max_length=100, verbose_name='Estado')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('marca_moto', models.CharField(max_length=100, verbose_name='Marca de la Motocicleta')),
                ('modelo_moto', models.CharField(max_length=100, verbose_name='Modelo')),
                ('año_moto', models.IntegerField(verbose_name='Año')),
                ('cilindrada', models.CharField(max_length=50, verbose_name='Cilindrada (cc)')),
                ('color_moto', models.CharField(max_length=50, verbose_name='Color')),
                ('placa', models.CharField(max_length=20, verbose_name='Placas')),
                ('años_experiencia', models.CharField(choices=[('menos_1', 'Menos de 1 año'), ('1_3', '1 a 3 años'), ('3_5', '3 a 5 años'), ('5_10', '5 a 10 años'), ('mas_10', 'Más de 10 años')], max_length=20, verbose_name='Años de Experiencia')),
                ('tiene_licencia', models.BooleanField(default=True, verbose_name='¿Cuenta con Licencia?')),
                ('numero_licencia', models.CharField(blank=True, max_length=50, verbose_name='Número de Licencia')),
                ('contacto_emergencia_nombre', models.CharField(max_length=200, verbose_name='Nombre del Contacto de Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(max_length=15, verbose_name='Teléfono de Emergencia')),
                ('contacto_emergencia_parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Adicionales')),
            ],
            options={
                'verbose_name': 'Motociclista',
                'verbose_name_plural': 'Motociclistas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
