# Generated by Django 6.0.5 on 2026-05-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motociclista',
            name='acepta_permiso_fotos',
            field=models.BooleanField(default=False, verbose_name='Acepto el Permiso de Fotografías'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='acepta_privacidad',
            field=models.BooleanField(default=False, verbose_name='Acepto la Política de Privacidad'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='acepta_responsabilidad',
            field=models.BooleanField(default=False, verbose_name='Acepto la Liberación de Responsabilidad Social'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='acepta_tratamiento_datos',
            field=models.BooleanField(default=False, verbose_name='Acepto el Tratamiento de Datos'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='alergico_especifique',
            field=models.CharField(blank=True, max_length=200, verbose_name='Especifique alergia'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Adjuntar Documentos'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='es_alergico',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Es alérgico a?'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='firma',
            field=models.TextField(blank=True, help_text='Datos de firma en formato base64', verbose_name='Firma de Conformidad'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='forma_suministro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Forma de suministro'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='foto_identificacion',
            field=models.FileField(blank=True, null=True, upload_to='identificaciones/', verbose_name='Adjuntar Foto de Identificación'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, verbose_name='Grupo Sanguíneo'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='medicamento_especifique',
            field=models.CharField(blank=True, max_length=200, verbose_name='Especifique medicamento'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='padecimiento_especifique',
            field=models.CharField(blank=True, max_length=200, verbose_name='Especifique padecimiento'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='padecimiento_fisico',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Sufre algún padecimiento físico?'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='seguro_especifique',
            field=models.CharField(blank=True, max_length=200, verbose_name='Especifique seguro'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='seguro_medico',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Posee seguro médico?'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='toma_medicamento',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Toma algún medicamento?'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='tratamiento_especifique',
            field=models.CharField(blank=True, max_length=200, verbose_name='Especifique tratamiento'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='tratamiento_medico',
            field=models.CharField(blank=True, choices=[('', 'Seleccionar'), ('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='¿Está bajo algún tratamiento médico?'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='vehiculo_modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vehículo Modelo'),
        ),
        migrations.AddField(
            model_name='motociclista',
            name='vehiculo_placa',
            field=models.CharField(blank=True, max_length=20, verbose_name='Vehículo Placa'),
        ),
    ]
